### ISSUE TITLE
Fix moving bar in pop-up bar

### ISSUE THREAD

**Issue by Jan-WillemD** [Jan-WillemD/8Trackers#9]
![image](https://cloud.githubusercontent.com/assets/20186245/19108777/7d586b54-8af2-11e6-9a80-9fb0b7c89427.png)

This bar is not necessary, and the pop-up will look nicer without it.

**Comment by whroman** [comment]
Browsers do that automatically. I'll put in some CSS to prevent that.

**Comment by whroman** [comment]
This works on my phone now. Try it out!
